http:
  host: 'localhost'
  port: 2001 

mongo:
  url: mongodb://localhost:27017/smart_house

mqtt: 
  url: mqtts://io.adafruit.com
  port: 8883
  username: hoductri
  password: aio_EUQX952NvvPAbPKxVayxoNh6TSDY
  keyMesure: 
    temprature: hoductri/feeds/bbc-temp
    moisture: hoductri/feeds/bbc-moisture
    gas: 	hoductri/feeds/bbc-gas
