http:
  host: 'localhost'
  port: 2001

mongo:
  url: mongodb://localhost:27017/smart_house

mqtt:
  url: mqtts://io.adafruit.com
  port: 8883
  username: hoductri
  password: aio_gvwK58mmBdvEAdI7HMqu5zZhzSlv
  key:
    temprature: bbc-temp
    moisture: bbc-moisture
    gas: bbc-gas
    firstLed: bbc-led
    buzzer: bbc-buzzer
    door: bbc-door
    pump: bbc-pump
    humidity: bbc-humi
