http:
  host: 'localhost'
  port: 2001 

mongo:
  url: mongodb://localhost:27017/smart_house

mqtt: 
  url: mqtts://io.adafruit.com
  port: 8883
  username: hoductri
  password: aio_ZhpF70RDQSfcNlPKTdP5jT70ejjp
  keyMesure: 
    temprature: hoductri/feeds/bbc-temp
